<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ZIPLSY1781" name="com.main.FlowEInvoice" tests="3" failures="0" timestamp="01 Oct 2018 13:32:20 GMT" time="109.895" errors="1">
  <testcase name="Login" time="61.737" classname="com.main.FlowEInvoice"/>
  <testcase name="InvoiceNonPO" time="44.714" classname="com.main.FlowEInvoice"/>
  <testcase name="InvoiceAction" time="3.444" classname="com.main.FlowEInvoice">
    <error type="java.lang.Exception">
      <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:221)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:144)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:153)
at com.main.FlowEInvoice.InvoiceAction(FlowEInvoice.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- InvoiceAction -->
</testsuite> <!-- com.main.FlowEInvoice -->
